### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by utkarsh2102** [rails/globalid#116]
```
RailtieTest#test_GlobalID.app_can_be_set_with_config.global_id.app_= = 0.43 s = E


Error:
RailtieTest#test_GlobalID.app_can_be_set_with_config.global_id.app_=:
Errno::ENOENT: No such file or directory @ rb_sysopen - /<<PKGBUILDDIR>>/tmp/development_secret.txt
    test/cases/railtie_test.rb:27:in `block in <class:RailtieTest>'

bin/rails test test/cases/railtie_test.rb:25


RailtieTest#test_GlobalID.app_for_Blog::Application_defaults_to_blog = 0.40 s = E


Error:
RailtieTest#test_GlobalID.app_for_Blog::Application_defaults_to_blog:
Errno::ENOENT: No such file or directory @ rb_sysopen - /<<PKGBUILDDIR>>/tmp/development_secret.txt
    test/cases/railtie_test.rb:21:in `block in <class:RailtieTest>'

bin/rails test test/cases/railtie_test.rb:20

RailtieTest#test_config.global_id_can_be_used_to_set_configurations_after_the_railtie_has_been_loaded = 0.44 s = E


Error:
RailtieTest#test_config.global_id_can_be_used_to_set_configurations_after_the_railtie_has_been_loaded:
Errno::ENOENT: No such file or directory @ rb_sysopen - /<<PKGBUILDDIR>>/tmp/development_secret.txt
    test/cases/railtie_test.rb:38:in `block in <class:RailtieTest>'

bin/rails test test/cases/railtie_test.rb:31


Finished in 1.367685s, 97.2446 runs/s, 174.7479 assertions/s.
133 runs, 239 assertions, 0 failures, 3 errors, 0 skips
```

**Comment by y-yagi** [comment]
Thanks for your report! I fixes with #117.
